// scripts/generate-keywords.ts
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const keywords: { keyword: string; category: string }[] = [
  // ===== ES・自己PR =====
  { keyword: '自己PR 書き方 文系', category: 'ES・自己PR' },
  { keyword: '自己PR 書き方 理系', category: 'ES・自己PR' },
  { keyword: '自己PR アルバイト経験', category: 'ES・自己PR' },
  { keyword: '自己PR 部活 経験', category: 'ES・自己PR' },
  { keyword: '自己PR リーダーシップ 例文', category: 'ES・自己PR' },
  { keyword: '自己PR チームワーク 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 継続力 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 短所 書き方', category: 'ES・自己PR' },
  { keyword: '自己PR 400字 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 600字 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 200字 例文', category: 'ES・自己PR' },
  { keyword: '自己PR ゼミ 研究', category: 'ES・自己PR' },
  { keyword: '自己PR インターン経験', category: 'ES・自己PR' },
  { keyword: '自己PR 強み 弱み セット', category: 'ES・自己PR' },
  { keyword: '自己PR 行動力 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 分析力 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 問題解決力 例文', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 書き方 ゼミ', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 書き方 サークル', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 書き方 アルバイト', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 書き方 留学', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 書き方 趣味', category: 'ES・自己PR' },
  { keyword: 'ガクチカ ない 就活', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 250字 例文', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 400字 例文', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 差別化 コツ', category: 'ES・自己PR' },
  { keyword: '志望動機 書き方 新卒 例文', category: 'ES・自己PR' },
  { keyword: '志望動機 業界 なぜ この会社', category: 'ES・自己PR' },
  { keyword: '志望動機 例文 メーカー', category: 'ES・自己PR' },
  { keyword: '志望動機 例文 IT企業', category: 'ES・自己PR' },
  { keyword: '志望動機 例文 金融', category: 'ES・自己PR' },
  { keyword: '志望動機 例文 商社', category: 'ES・自己PR' },
  { keyword: '志望動機 例文 コンサル', category: 'ES・自己PR' },
  { keyword: '志望動機 例文 公務員', category: 'ES・自己PR' },
  { keyword: 'ES 通過率 高い 書き方', category: 'ES・自己PR' },
  { keyword: 'ES 書き方 構成 STAR', category: 'ES・自己PR' },
  { keyword: 'ES コピペ 注意点', category: 'ES・自己PR' },
  { keyword: 'ES 自己PR ガクチカ 違い', category: 'ES・自己PR' },
  { keyword: 'ES 添削 無料 サービス', category: 'ES・自己PR' },
  { keyword: 'ES 提出 遅れた 対処法', category: 'ES・自己PR' },
  { keyword: 'ES 写真 撮り方 就活', category: 'ES・自己PR' },
  { keyword: 'エントリーシート 書き方 コツ', category: 'ES・自己PR' },
  { keyword: 'エントリーシート 例文 大学生', category: 'ES・自己PR' },
  { keyword: 'エントリーシート 落ちる 理由', category: 'ES・自己PR' },
  { keyword: '自己分析 やり方 就活', category: 'ES・自己PR' },
  { keyword: '自己分析 ツール 無料 おすすめ', category: 'ES・自己PR' },
  { keyword: '自己分析 強み 見つけ方', category: 'ES・自己PR' },
  { keyword: '自己分析 弱み 例', category: 'ES・自己PR' },
  { keyword: '自己分析 マッチング 企業選び', category: 'ES・自己PR' },
  { keyword: '強み 弱み 就活 例文 一覧', category: 'ES・自己PR' },
  { keyword: '強み 継続力 アピール 方法', category: 'ES・自己PR' },
  { keyword: '強み 協調性 例文', category: 'ES・自己PR' },
  { keyword: '短所 面接 一覧 言い換え', category: 'ES・自己PR' },
  { keyword: '短所 心配性 面接 例文', category: 'ES・自己PR' },
  { keyword: '短所 完璧主義 面接 例文', category: 'ES・自己PR' },
  { keyword: '短所 優柔不断 面接 例文', category: 'ES・自己PR' },
  { keyword: '他己分析 やり方 就活', category: 'ES・自己PR' },
  { keyword: 'STAR法 自己PR 書き方', category: 'ES・自己PR' },
  { keyword: '就活 自己PR 刺さる 例文', category: 'ES・自己PR' },
  { keyword: '就活 ES 何社 出すべき', category: 'ES・自己PR' },
  { keyword: '就活 添削 OB OG 頼み方', category: 'ES・自己PR' },
  { keyword: 'OpenES 書き方 ポイント', category: 'ES・自己PR' },
  { keyword: 'OpenES 写真 スーツ 注意', category: 'ES・自己PR' },
  { keyword: 'マイナビ ES 書き方 コツ', category: 'ES・自己PR' },
  { keyword: 'リクナビ ES 書き方 通過', category: 'ES・自己PR' },
  { keyword: '自己PR 人見知り 克服 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 負けず嫌い 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 好奇心旺盛 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 真面目 例文', category: 'ES・自己PR' },
  { keyword: '自己PR 計画性 例文', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 複数 書き方 コツ', category: 'ES・自己PR' },
  { keyword: 'ガクチカ 研究 例文 理系', category: 'ES・自己PR' },
  { keyword: 'ガクチカ ボランティア 例文', category: 'ES・自己PR' },
  { keyword: 'ES 結論ファースト 書き方', category: 'ES・自己PR' },
  { keyword: '就活 自己PR 面接 ずれる 対策', category: 'ES・自己PR' },
  { keyword: '就活 自己PR 文字数 目安', category: 'ES・自己PR' },
  { keyword: '就活 自己PR 書けない 理由', category: 'ES・自己PR' },

  // ===== 面接対策 =====
  { keyword: '面接 逆質問 例文 新卒', category: '面接対策' },
  { keyword: 'グループディスカッション コツ 通過', category: '面接対策' },
  { keyword: '面接 自己紹介 1分 例文', category: '面接対策' },
  { keyword: '最終面接 対策 逆転', category: '面接対策' },
  { keyword: 'オンライン面接 注意点 背景', category: '面接対策' },
  { keyword: '面接 よく聞かれる 質問 一覧', category: '面接対策' },
  { keyword: '面接 緊張 対策 コツ', category: '面接対策' },
  { keyword: '面接 マナー 入室 退室', category: '面接対策' },
  { keyword: '面接 服装 女性 スーツ', category: '面接対策' },
  { keyword: '面接 服装 男性 スーツ 色', category: '面接対策' },
  { keyword: '面接 髪型 女性 ポイント', category: '面接対策' },
  { keyword: '面接 髪型 男性 清潔感', category: '面接対策' },
  { keyword: '面接 入室 ノック 回数', category: '面接対策' },
  { keyword: '面接 時間 何分前 到着', category: '面接対策' },
  { keyword: '面接 遅刻 連絡 メール', category: '面接対策' },
  { keyword: '面接 キャンセル 連絡 メール 例文', category: '面接対策' },
  { keyword: '一次面接 通過率 平均', category: '面接対策' },
  { keyword: '二次面接 対策 変わること', category: '面接対策' },
  { keyword: '最終面接 落ちる 理由', category: '面接対策' },
  { keyword: '最終面接 フォロー メール 例文', category: '面接対策' },
  { keyword: 'グループディスカッション 役割 書記', category: '面接対策' },
  { keyword: 'グループディスカッション 役割 司会', category: '面接対策' },
  { keyword: 'グループディスカッション タイムキーパー コツ', category: '面接対策' },
  { keyword: 'グループディスカッション 発言 できない 対策', category: '面接対策' },
  { keyword: 'グループディスカッション テーマ 一覧', category: '面接対策' },
  { keyword: 'グループディスカッション 評価 ポイント', category: '面接対策' },
  { keyword: '面接 強み 弱み 答え方', category: '面接対策' },
  { keyword: '面接 学生時代 頑張ったこと 答え方', category: '面接対策' },
  { keyword: '面接 志望理由 答え方 コツ', category: '面接対策' },
  { keyword: '面接 将来 どうなりたい 答え方', category: '面接対策' },
  { keyword: '面接 5年後 10年後 答え方', category: '面接対策' },
  { keyword: '面接 趣味 答え方 例文', category: '面接対策' },
  { keyword: '面接 最近気になる ニュース 答え方', category: '面接対策' },
  { keyword: '面接 他社の選考 答え方', category: '面接対策' },
  { keyword: '面接 内定 他社 答え方', category: '面接対策' },
  { keyword: '面接 圧迫面接 対策 対処法', category: '面接対策' },
  { keyword: '面接 沈黙 対処法', category: '面接対策' },
  { keyword: '面接 敬語 注意 ミス', category: '面接対策' },
  { keyword: '面接 お礼メール 送る 送らない', category: '面接対策' },
  { keyword: '面接 お礼メール 例文 当日', category: '面接対策' },
  { keyword: 'オンライン面接 部屋 背景 整え方', category: '面接対策' },
  { keyword: 'オンライン面接 カメラ 目線 コツ', category: '面接対策' },
  { keyword: 'オンライン面接 通信 安定 方法', category: '面接対策' },
  { keyword: 'オンライン面接 音声 マイク おすすめ', category: '面接対策' },
  { keyword: 'Zoom 面接 やり方 初めて', category: '面接対策' },
  { keyword: 'Teams 面接 注意点', category: '面接対策' },
  { keyword: '録画面接 コツ 答え方', category: '面接対策' },
  { keyword: 'AI面接 対策 コツ', category: '面接対策' },
  { keyword: '面接 練習 方法 独学', category: '面接対策' },
  { keyword: '面接 練習 無料 サービス', category: '面接対策' },
  { keyword: '模擬面接 就活 どこで やる', category: '面接対策' },
  { keyword: '面接 フィードバック 就活エージェント', category: '面接対策' },
  { keyword: '面接 落ちる 理由 わからない', category: '面接対策' },
  { keyword: '面接 通過 サイン 見分け方', category: '面接対策' },
  { keyword: '面接 結果 連絡 遅い 理由', category: '面接対策' },
  { keyword: '面接 複数日程 候補日 メール 返し方', category: '面接対策' },
  { keyword: '面接 日程 変更 メール 例文', category: '面接対策' },
  { keyword: '集団面接 対策 個別との違い', category: '面接対策' },
  { keyword: '面接 笑顔 作り方 コツ', category: '面接対策' },
  { keyword: '面接 声 大きさ 話し方', category: '面接対策' },
  { keyword: '面接 言葉 つかえる 対処法', category: '面接対策' },
  { keyword: '面接 うまく話せない 原因', category: '面接対策' },
  { keyword: '面接 受かるには 何が必要', category: '面接対策' },
  { keyword: '内定 承諾 メール 例文', category: '面接対策' },
  { keyword: '内定 辞退 メール 例文 新卒', category: '面接対策' },
  { keyword: '内定 複数 断り方', category: '面接対策' },
  { keyword: '内定 保留 期間 限界', category: '面接対策' },
  { keyword: '内定 後 やること リスト', category: '面接対策' },
  { keyword: '面接 準備 前日 チェックリスト', category: '面接対策' },
  { keyword: '面接 当日 持ち物 確認', category: '面接対策' },
  { keyword: '面接 スーツ 購入 いつ', category: '面接対策' },
  { keyword: '面接 バッグ 選び方 就活', category: '面接対策' },
  { keyword: '面接 靴 選び方 就活', category: '面接対策' },
  { keyword: '面接 メイク 就活 女性', category: '面接対策' },
  { keyword: '面接 ネクタイ 色 就活', category: '面接対策' },
  { keyword: '面接 シャツ 色 就活', category: '面接対策' },
  { keyword: '面接 香水 注意点', category: '面接対策' },
  { keyword: '面接 アクセサリー 就活 マナー', category: '面接対策' },

  // ===== インターン =====
  { keyword: 'インターン 志望動機 書き方 コツ', category: 'インターン' },
  { keyword: 'インターン 服装 夏 私服 選び方', category: 'インターン' },
  { keyword: 'インターン メール 辞退 例文', category: 'インターン' },
  { keyword: '短期インターン 意味ない 理由', category: 'インターン' },
  { keyword: 'インターン 落ちた 原因 対策', category: 'インターン' },
  { keyword: 'インターン 2年生 参加 メリット', category: 'インターン' },
  { keyword: 'インターン 3年生 いつから 準備', category: 'インターン' },
  { keyword: 'インターン 参加 した ほうがいい 理由', category: 'インターン' },
  { keyword: 'インターン 夏 秋 冬 違い', category: 'インターン' },
  { keyword: 'インターン 1day 意味 メリット', category: 'インターン' },
  { keyword: 'インターン 1week 内容 学べること', category: 'インターン' },
  { keyword: 'インターン 長期 短期 どちらがいい', category: 'インターン' },
  { keyword: 'インターン 選考 通過 率 平均', category: 'インターン' },
  { keyword: 'インターン 優遇 本選考 ルート', category: 'インターン' },
  { keyword: 'インターン 有給 バイト代 相場', category: 'インターン' },
  { keyword: 'インターン ES 書き方 新卒', category: 'インターン' },
  { keyword: 'インターン ES 志望動機 例文', category: 'インターン' },
  { keyword: 'インターン ES ガクチカ 必要', category: 'インターン' },
  { keyword: 'インターン 面接 対策 質問', category: 'インターン' },
  { keyword: 'インターン 面接 逆質問 例文', category: 'インターン' },
  { keyword: 'インターン 感想 メール 例文', category: 'インターン' },
  { keyword: 'インターン 報告 レポート 書き方', category: 'インターン' },
  { keyword: 'インターン 日誌 書き方 例文', category: 'インターン' },
  { keyword: 'インターン お礼 メール 翌日 例文', category: 'インターン' },
  { keyword: 'インターン 終了後 本選考 案内', category: 'インターン' },
  { keyword: 'インターン 評価 された 確認 方法', category: 'インターン' },
  { keyword: 'インターン 交通費 支給 確認 方法', category: 'インターン' },
  { keyword: 'インターン 欠席 連絡 メール 例文', category: 'インターン' },
  { keyword: 'インターン 遅刻 連絡 対処法', category: 'インターン' },
  { keyword: '大手 インターン 倍率 高い 対策', category: 'インターン' },
  { keyword: 'コンサル インターン 対策 ケース', category: 'インターン' },
  { keyword: '商社 インターン 選考 流れ', category: 'インターン' },
  { keyword: '金融 インターン 選考 対策', category: 'インターン' },
  { keyword: 'IT インターン 未経験 参加 可能', category: 'インターン' },
  { keyword: 'ベンチャー インターン メリット デメリット', category: 'インターン' },
  { keyword: 'スタートアップ インターン 就活 有利', category: 'インターン' },
  { keyword: '外資系 インターン 選考 対策', category: 'インターン' },
  { keyword: 'マスコミ インターン 倍率 対策', category: 'インターン' },
  { keyword: '広告代理店 インターン 就活 つながり', category: 'インターン' },
  { keyword: 'インターン 何社 参加 理想', category: 'インターン' },
  { keyword: 'インターン 経験 ES 活かし方', category: 'インターン' },
  { keyword: 'インターン ガクチカ 書き方', category: 'インターン' },
  { keyword: 'インターン 選考 グループワーク 対策', category: 'インターン' },
  { keyword: 'インターン 選考 適性検査 種類', category: 'インターン' },
  { keyword: 'インターン 事前課題 提出 注意点', category: 'インターン' },
  { keyword: 'インターン 当日 服装 スーツ 私服', category: 'インターン' },
  { keyword: 'インターン 名刺 もらう マナー', category: 'インターン' },
  { keyword: 'インターン 社員 積極的 話しかける コツ', category: 'インターン' },
  { keyword: 'インターン 緊張 対処法', category: 'インターン' },
  { keyword: 'インターン 成果 アピール 方法', category: 'インターン' },
  { keyword: '長期インターン 大学生 探し方', category: 'インターン' },
  { keyword: '長期インターン 掛け持ち 可能 注意', category: 'インターン' },
  { keyword: '長期インターン 就活 有利 本当', category: 'インターン' },
  { keyword: '長期インターン 給料 相場 東京', category: 'インターン' },
  { keyword: '長期インターン 辞め方 礼儀', category: 'インターン' },
  { keyword: 'インターン 応募 いつ 時期', category: 'インターン' },
  { keyword: 'インターン 締切 いつまで 探す', category: 'インターン' },
  { keyword: 'インターン まとめサイト おすすめ', category: 'インターン' },
  { keyword: 'インターン 倍率 低い 業界', category: 'インターン' },
  { keyword: 'インターン 受かるには 何をすれば', category: 'インターン' },
  { keyword: 'インターン 不合格 お礼 必要', category: 'インターン' },
  { keyword: 'インターン 複数 参加 管理 方法', category: 'インターン' },
  { keyword: 'インターン 旅費 宿泊費 支給', category: 'インターン' },
  { keyword: 'インターン 1年生 参加 できる', category: 'インターン' },
  { keyword: 'インターン 合同 説明会 活用法', category: 'インターン' },
  { keyword: 'インターン 就活 サイト 使い方', category: 'インターン' },
  { keyword: 'インターン 探す 方法 おすすめ', category: 'インターン' },
  { keyword: 'インターン 辞退 マナー 期限', category: 'インターン' },
  { keyword: 'インターン 口コミ 調べ方', category: 'インターン' },
  { keyword: 'インターン 感想 ブログ 参考', category: 'インターン' },
  { keyword: 'インターン 人事 担当 メール 書き方', category: 'インターン' },
  { keyword: 'インターン 振り返り シート 書き方', category: 'インターン' },
  { keyword: 'インターン 初日 注意 持ち物', category: 'インターン' },
  { keyword: 'インターン 参加 メリット 一覧', category: 'インターン' },
  { keyword: 'インターン 志望動機 なぜ 御社', category: 'インターン' },

  // ===== 就活サイト比較 =====
  { keyword: 'マイナビ リクナビ 違い 徹底比較', category: '就活サイト比較' },
  { keyword: '就活サイト おすすめ 2026 ランキング', category: '就活サイト比較' },
  { keyword: 'キャリアチケット 評判 口コミ 内定率', category: '就活サイト比較' },
  { keyword: 'OfferBox 使い方 登録 コツ', category: '就活サイト比較' },
  { keyword: 'ビズリーチ 学生 評判 使い方', category: '就活サイト比較' },
  { keyword: 'doda キャンパス 評判 新卒', category: '就活サイト比較' },
  { keyword: 'Wantedly 新卒 使い方 コツ', category: '就活サイト比較' },
  { keyword: 'リクルーター 来た 対応 方法', category: '就活サイト比較' },
  { keyword: 'マイナビ 2026 登録 方法 使い方', category: '就活サイト比較' },
  { keyword: 'リクナビ 2026 登録 方法 使い方', category: '就活サイト比較' },
  { keyword: '逆オファー サイト 比較 おすすめ', category: '就活サイト比較' },
  { keyword: 'キミスカ 使い方 評判', category: '就活サイト比較' },
  { keyword: 'あさがくナビ 評判 おすすめ', category: '就活サイト比較' },
  { keyword: '就活会議 口コミ 信頼性', category: '就活サイト比較' },
  { keyword: 'ワンキャリア 評判 使い方', category: '就活サイト比較' },
  { keyword: 'ワンキャリア ES 閲覧 無料', category: '就活サイト比較' },
  { keyword: '就活エージェント おすすめ 新卒', category: '就活サイト比較' },
  { keyword: '就活エージェント 使い方 流れ', category: '就活サイト比較' },
  { keyword: '就活エージェント 怖い 押しつけ 断り方', category: '就活サイト比較' },
  { keyword: '就活エージェント 複数 利用 メリット', category: '就活サイト比較' },
  { keyword: 'irootsとは 評判 スカウト', category: '就活サイト比較' },
  { keyword: 'Matcher 就活 OB訪問 評判', category: '就活サイト比較' },
  { keyword: 'ミーツカンパニー 評判 就活', category: '就活サイト比較' },
  { keyword: '外資就活 ドットコム 使い方 コツ', category: '就活サイト比較' },
  { keyword: '就活 掲示板 おすすめ 2ちゃんねる', category: '就活サイト比較' },
  { keyword: 'ABABA 評判 就活 落ちたら', category: '就活サイト比較' },
  { keyword: 'Moffly 就活 スカウト 評判', category: '就活サイト比較' },
  { keyword: '就活 ナビサイト 複数 登録 メリット', category: '就活サイト比較' },
  { keyword: '就活 サイト 登録 いつから 2026', category: '就活サイト比較' },
  { keyword: '就活 サイト 無料 有料 違い', category: '就活サイト比較' },
  { keyword: '就活 サイト 使いすぎ 疲れる 整理', category: '就活サイト比較' },
  { keyword: 'マイナビ 有料プラン 価値 あるか', category: '就活サイト比較' },
  { keyword: 'マイナビ スカウト 来ない 理由', category: '就活サイト比較' },
  { keyword: 'リクナビ プレエントリー 意味 効果', category: '就活サイト比較' },
  { keyword: 'マイナビ リクナビ どちら メイン', category: '就活サイト比較' },
  { keyword: '就活 口コミサイト 正直 信頼', category: '就活サイト比較' },
  { keyword: '就活 動画 面接 サービス 比較', category: '就活サイト比較' },
  { keyword: '就活 AI 面接 練習 無料', category: '就活サイト比較' },
  { keyword: '就活 キャリア相談 無料 おすすめ', category: '就活サイト比較' },
  { keyword: '就活 合同説明会 オンライン おすすめ', category: '就活サイト比較' },
  { keyword: '就活 説明会 予約 方法', category: '就活サイト比較' },
  { keyword: '就活 企業 説明会 服装', category: '就活サイト比較' },
  { keyword: '就活 説明会 質問 例文', category: '就活サイト比較' },
  { keyword: '就活 OB訪問 アプリ 比較', category: '就活サイト比較' },
  { keyword: '就活 ポートフォリオ サイト 作り方', category: '就活サイト比較' },
  { keyword: '就活 メール 返信 マナー', category: '就活サイト比較' },
  { keyword: '就活 Twitter X 活用 方法', category: '就活サイト比較' },
  { keyword: '就活 LINE 使い方 企業', category: '就活サイト比較' },
  { keyword: '就活 SNS 使い方 トラブル', category: '就活サイト比較' },
  { keyword: 'キャリタス就活 使い方 評判', category: '就活サイト比較' },
  { keyword: 'ニュキャリ 評判 新卒', category: '就活サイト比較' },
  { keyword: 'リクルートエージェント 新卒 使える', category: '就活サイト比較' },
  { keyword: '就活 フォロー 電話 対応 方法', category: '就活サイト比較' },
  { keyword: '就活 LINE公式 ブロック マナー', category: '就活サイト比較' },
  { keyword: '就活サイト 怪しい 見分け方', category: '就活サイト比較' },
  { keyword: '就活サイト 個人情報 取り扱い 注意', category: '就活サイト比較' },
  { keyword: 'JobSpring 評判 就活', category: '就活サイト比較' },
  { keyword: 'カリクル 評判 就活サイト', category: '就活サイト比較' },
  { keyword: 'LabBase 理系 就活 評判', category: '就活サイト比較' },
  { keyword: 'リサーチパネル 就活 データ 調査', category: '就活サイト比較' },
  { keyword: '就活 就職浪人 サイト 使い方', category: '就活サイト比較' },
  { keyword: '就活 早期選考 サイト 特定 方法', category: '就活サイト比較' },
  { keyword: '就活 逆求人 何社 登録', category: '就活サイト比較' },
  { keyword: '就活サイト プロフィール 写真 コツ', category: '就活サイト比較' },
  { keyword: '就活サイト スカウト 返信 しなくていい', category: '就活サイト比較' },
  { keyword: '就活サイト 登録 何月 理想', category: '就活サイト比較' },
  { keyword: '就活 情報 収集 方法 まとめ', category: '就活サイト比較' },
  { keyword: '就活 アプリ おすすめ 管理 スケジュール', category: '就活サイト比較' },
  { keyword: '就活 ノート まとめ 方法', category: '就活サイト比較' },
  { keyword: '就活 スプレッドシート 管理 テンプレ', category: '就活サイト比較' },
  { keyword: '就活 企業 エントリー 数 平均', category: '就活サイト比較' },
  { keyword: '就活 内定 もらいやすい サイト', category: '就活サイト比較' },
  { keyword: '就活 サイト 全部 登録 疲れる', category: '就活サイト比較' },
  { keyword: '就活 プレエントリー 意味 タイミング', category: '就活サイト比較' },
  { keyword: '就活 採用 ページ 直接 応募 メリット', category: '就活サイト比較' },
  { keyword: '就活 スカウト 怪しい 見分け方', category: '就活サイト比較' },
  { keyword: '就活 サイト 解約 退会 方法', category: '就活サイト比較' },

  // ===== SPI・筆記試験 =====
  { keyword: 'SPI 勉強 方法 独学 2026', category: 'SPI・筆記試験' },
  { keyword: 'SPI 問題集 おすすめ 参考書', category: 'SPI・筆記試験' },
  { keyword: 'SPI 非言語 苦手 克服 方法', category: 'SPI・筆記試験' },
  { keyword: 'SPI 言語 対策 コツ', category: 'SPI・筆記試験' },
  { keyword: 'SPI 足切り 基準 平均', category: 'SPI・筆記試験' },
  { keyword: 'SPI 受験形式 テストセンター 自宅', category: 'SPI・筆記試験' },
  { keyword: 'テストセンター SPI 受け直し 方法', category: 'SPI・筆記試験' },
  { keyword: 'テストセンター 当日 流れ 注意点', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト 種類 一覧 違い', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト SPI 玉手箱 違い', category: 'SPI・筆記試験' },
  { keyword: '玉手箱 対策 問題集 おすすめ', category: 'SPI・筆記試験' },
  { keyword: '玉手箱 計数 時間 配分', category: 'SPI・筆記試験' },
  { keyword: 'GAB テスト 対策 勉強法', category: 'SPI・筆記試験' },
  { keyword: 'CAB テスト 対策 IT企業', category: 'SPI・筆記試験' },
  { keyword: 'TG-WEB 対策 難しい 問題', category: 'SPI・筆記試験' },
  { keyword: 'SPI 性格検査 対策 嘘 ばれる', category: 'SPI・筆記試験' },
  { keyword: 'SPI 性格検査 落ちる 理由', category: 'SPI・筆記試験' },
  { keyword: 'SPI 能力検査 時間 配分 テクニック', category: 'SPI・筆記試験' },
  { keyword: 'SPI 推論 問題 コツ', category: 'SPI・筆記試験' },
  { keyword: 'SPI 集合 問題 解き方', category: 'SPI・筆記試験' },
  { keyword: 'SPI 速さ 距離 時間 問題', category: 'SPI・筆記試験' },
  { keyword: 'SPI 割合 問題 苦手', category: 'SPI・筆記試験' },
  { keyword: 'SPI 確率 問題 解き方', category: 'SPI・筆記試験' },
  { keyword: 'SPI 語彙 問題 対策', category: 'SPI・筆記試験' },
  { keyword: 'SPI 文章読解 問題 スピード', category: 'SPI・筆記試験' },
  { keyword: 'SPI 英語 対策 難易度', category: 'SPI・筆記試験' },
  { keyword: 'SPI スコア 何点 基準 大手', category: 'SPI・筆記試験' },
  { keyword: 'SPI 無料 練習 サイト', category: 'SPI・筆記試験' },
  { keyword: 'SPI アプリ 無料 おすすめ', category: 'SPI・筆記試験' },
  { keyword: 'SPI 何週間 勉強 必要', category: 'SPI・筆記試験' },
  { keyword: 'SPI 理系 文系 難易度 違い', category: 'SPI・筆記試験' },
  { keyword: 'SPI 3 内容 旧バージョンとの違い', category: 'SPI・筆記試験' },
  { keyword: 'SPI テストセンター スコア 使い回し', category: 'SPI・筆記試験' },
  { keyword: 'SPI 自宅受験 不正 ばれる', category: 'SPI・筆記試験' },
  { keyword: 'SPI 友人 代行 不正 リスク', category: 'SPI・筆記試験' },
  { keyword: 'SPI 採用 どのくらい 影響', category: 'SPI・筆記試験' },
  { keyword: '就活 適性検査 種類 企業', category: 'SPI・筆記試験' },
  { keyword: '筆記試験 就活 一般常識 対策', category: 'SPI・筆記試験' },
  { keyword: '一般常識 問題集 就活 おすすめ', category: 'SPI・筆記試験' },
  { keyword: '時事問題 就活 2026 対策', category: 'SPI・筆記試験' },
  { keyword: '就活 ニュース チェック 方法 毎日', category: 'SPI・筆記試験' },
  { keyword: 'クレペリン検査 対策 コツ', category: 'SPI・筆記試験' },
  { keyword: '内田クレペリン 就活 対策', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト 時間 足りない 対策', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト 就活 何社 課せられる', category: 'SPI・筆記試験' },
  { keyword: 'SPIと玉手箱 どちら 多い 業界', category: 'SPI・筆記試験' },
  { keyword: 'マイナビ テスト 種類 確認方法', category: 'SPI・筆記試験' },
  { keyword: '就活 筆記試験 持ち物 当日 注意', category: 'SPI・筆記試験' },
  { keyword: 'SPI 直前 追い込み 方法', category: 'SPI・筆記試験' },
  { keyword: 'SPI 制限時間 内 解き切る コツ', category: 'SPI・筆記試験' },
  { keyword: 'テストセンター 予約 取り方 満員', category: 'SPI・筆記試験' },
  { keyword: 'テストセンター 当日 持ち物 必要なもの', category: 'SPI・筆記試験' },
  { keyword: 'テストセンター 都内 場所 一覧', category: 'SPI・筆記試験' },
  { keyword: 'SPI 英語 問題 出る 業界', category: 'SPI・筆記試験' },
  { keyword: 'SPI 対策 1ヶ月 スケジュール', category: 'SPI・筆記試験' },
  { keyword: 'SPI 対策 3ヶ月 計画 立て方', category: 'SPI・筆記試験' },
  { keyword: 'SPI 問題 パターン 覚える 方法', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト 攻略 就活 サイト', category: 'SPI・筆記試験' },
  { keyword: '玉手箱 言語 対策 問題集', category: 'SPI・筆記試験' },
  { keyword: 'SCOA 試験 対策 問題', category: 'SPI・筆記試験' },
  { keyword: 'eF-1G テスト 対策 問題', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト 就活 ズル 代行 リスク', category: 'SPI・筆記試験' },
  { keyword: 'SPI デジタル 化 最新 情報', category: 'SPI・筆記試験' },
  { keyword: '就活 テスト 難易度 ランキング', category: 'SPI・筆記試験' },
  { keyword: '就活 テスト 対策 期間 いつから', category: 'SPI・筆記試験' },
  { keyword: 'SPI 全部 わからない 時 捨て方', category: 'SPI・筆記試験' },
  { keyword: 'SPI 問題 難易度 変動 傾向', category: 'SPI・筆記試験' },
  { keyword: 'SPI 回数 受け直し 何回', category: 'SPI・筆記試験' },
  { keyword: 'SPI 答え 合わせ できない 理由', category: 'SPI・筆記試験' },
  { keyword: 'Webテスト 終わった 後 何をすべき', category: 'SPI・筆記試験' },
  { keyword: '就活 数学 苦手 SPI 対策', category: 'SPI・筆記試験' },
  { keyword: '就活 国語 苦手 SPI 言語 対策', category: 'SPI・筆記試験' },
  { keyword: 'SPI 模擬 試験 無料 サイト', category: 'SPI・筆記試験' },
  { keyword: '就活 テスト センター 予約 早い', category: 'SPI・筆記試験' },
  { keyword: 'SPI 図形 問題 空間 把握 対策', category: 'SPI・筆記試験' },

  // ===== 就活マナー =====
  { keyword: '就活 メール 書き方 基本 マナー', category: '就活マナー' },
  { keyword: '就活 メール 件名 書き方 例', category: '就活マナー' },
  { keyword: '就活 メール 返信 マナー 遅れた', category: '就活マナー' },
  { keyword: '就活 メール 敬語 一覧 使い方', category: '就活マナー' },
  { keyword: '就活 メール 添付 ファイル 送り方', category: '就活マナー' },
  { keyword: '就活 メール 署名 書き方', category: '就活マナー' },
  { keyword: '就活 メール お礼 例文 面接後', category: '就活マナー' },
  { keyword: '就活 電話 かけ方 時間帯 マナー', category: '就活マナー' },
  { keyword: '就活 電話 受け方 折り返し 例文', category: '就活マナー' },
  { keyword: '就活 電話 担当者 不在 メッセージ', category: '就活マナー' },
  { keyword: '就活 電話 緊張 対処法', category: '就活マナー' },
  { keyword: '就活 敬語 使い方 間違い 一覧', category: '就活マナー' },
  { keyword: '就活 敬語 間違いやすい 言葉', category: '就活マナー' },
  { keyword: '就活 言葉遣い チェック リスト', category: '就活マナー' },
  { keyword: '就活 スーツ 選び方 男性 色', category: '就活マナー' },
  { keyword: '就活 スーツ 選び方 女性 おすすめ', category: '就活マナー' },
  { keyword: '就活 スーツ いつ 購入 タイミング', category: '就活マナー' },
  { keyword: '就活 スーツ ブランド 安い コスパ', category: '就活マナー' },
  { keyword: '就活 バッグ 選び方 素材 色', category: '就活マナー' },
  { keyword: '就活 靴 選び方 パンプス ヒール 高さ', category: '就活マナー' },
  { keyword: '就活 ストッキング 色 マナー', category: '就活マナー' },
  { keyword: '就活 メイク 自然 コツ 女性', category: '就活マナー' },
  { keyword: '就活 髪型 前髪 ポイント 女性', category: '就活マナー' },
  { keyword: '就活 髪型 セット 方法 男性', category: '就活マナー' },
  { keyword: '就活 髪色 茶髪 NG 黒染め', category: '就活マナー' },
  { keyword: '就活 ネイル マナー 透明 OK', category: '就活マナー' },
  { keyword: '就活 アクセサリー どこまで 許容', category: '就活マナー' },
  { keyword: '就活 ピアス 男性 外す 必要', category: '就活マナー' },
  { keyword: '就活 香水 付けない 理由', category: '就活マナー' },
  { keyword: '就活 写真 スタジオ 値段 おすすめ', category: '就活マナー' },
  { keyword: '就活 証明写真 撮り方 コツ', category: '就活マナー' },
  { keyword: '就活 証明写真 スマホ 撮影 方法', category: '就活マナー' },
  { keyword: '就活 説明会 マナー 服装 質問', category: '就活マナー' },
  { keyword: '就活 説明会 メモ 取り方 コツ', category: '就活マナー' },
  { keyword: '就活 説明会 遅刻 対処法', category: '就活マナー' },
  { keyword: '就活 選考辞退 マナー タイミング', category: '就活マナー' },
  { keyword: '就活 内定辞退 連絡 方法 マナー', category: '就活マナー' },
  { keyword: '就活 お礼状 封書 書き方', category: '就活マナー' },
  { keyword: '就活 封筒 書き方 マナー 縦書き', category: '就活マナー' },
  { keyword: '就活 書類 送り方 添え状', category: '就活マナー' },
  { keyword: '就活 書類 コピー 注意', category: '就活マナー' },
  { keyword: '就活 書類 封筒 大きさ 選び方', category: '就活マナー' },
  { keyword: '就活 SNS 鍵垢 必要 理由', category: '就活マナー' },
  { keyword: '就活 SNS 企業 チェック 対策', category: '就活マナー' },
  { keyword: '就活 名刺 受け取り方 マナー', category: '就活マナー' },
  { keyword: '就活 お辞儀 角度 マナー', category: '就活マナー' },
  { keyword: '就活 エレベーター 乗り方 マナー', category: '就活マナー' },
  { keyword: '就活 受付 挨拶 言い方', category: '就活マナー' },
  { keyword: '就活 待合室 過ごし方 マナー', category: '就活マナー' },
  { keyword: '就活 スマホ 面接中 マナー', category: '就活マナー' },
  { keyword: '就活 交通費 精算 方法 マナー', category: '就活マナー' },
  { keyword: '就活 昼食 食事 場所 マナー', category: '就活マナー' },
  { keyword: '就活 OB訪問 お礼 メール 例文', category: '就活マナー' },
  { keyword: '就活 懇親会 マナー お酒 断り方', category: '就活マナー' },
  { keyword: '就活 グループワーク マナー 発言', category: '就活マナー' },
  { keyword: '就活 ビジネスマナー 基本 一覧', category: '就活マナー' },
  { keyword: '就活 失礼 行動 NGリスト', category: '就活マナー' },
  { keyword: '就活 連絡 無視 される 対処法', category: '就活マナー' },
  { keyword: '就活 企業 メール くる 返信 必要', category: '就活マナー' },
  { keyword: '就活 電話 知らない 番号 出る', category: '就活マナー' },
  { keyword: '就活 内定 メール 返信 例文', category: '就活マナー' },
  { keyword: '就活 内定 電話 受け方 返事', category: '就活マナー' },
  { keyword: '就活 書類選考 通過 連絡 来ない', category: '就活マナー' },
  { keyword: '就活 企業 個人情報 聞かれる 対応', category: '就活マナー' },
  { keyword: '就活 録音 面接 法律 大丈夫', category: '就活マナー' },
  { keyword: '就活 お祈りメール 返信 必要', category: '就活マナー' },
  { keyword: '就活 お祈り後 再チャレンジ 可能', category: '就活マナー' },
  { keyword: '就活 社員 名前 忘れた 対処法', category: '就活マナー' },
  { keyword: '就活 挨拶 社員 すれ違い 声かけ', category: '就活マナー' },
  { keyword: '就活 スーツ 洗濯 頻度 方法', category: '就活マナー' },
  { keyword: '就活 ワイシャツ アイロン かけ方', category: '就活マナー' },
  { keyword: '就活 カバン 中身 整理 何入れる', category: '就活マナー' },
  { keyword: '就活 モバイル充電 持参 マナー', category: '就活マナー' },
  { keyword: '就活 交通IC 精算 ポイント 注意', category: '就活マナー' },
  { keyword: '就活 上座 下座 会議室 マナー', category: '就活マナー' },

  // ===== 業界研究 =====
  { keyword: '業界研究 やり方 就活 ステップ', category: '業界研究' },
  { keyword: '業界研究 本 おすすめ 就活', category: '業界研究' },
  { keyword: '業界研究 まとめ方 ノート', category: '業界研究' },
  { keyword: 'IT業界 就活 ランキング 2026', category: '業界研究' },
  { keyword: 'メーカー 業界 就活 仕事内容', category: '業界研究' },
  { keyword: '金融業界 就活 銀行 証券 保険 違い', category: '業界研究' },
  { keyword: '商社 業界 仕事内容 総合 専門', category: '業界研究' },
  { keyword: 'コンサル 業界 種類 違い 仕事', category: '業界研究' },
  { keyword: 'マスコミ 業界 就活 倍率 難易度', category: '業界研究' },
  { keyword: '広告 業界 就活 仕事内容 特徴', category: '業界研究' },
  { keyword: '不動産 業界 就活 仕事内容 魅力', category: '業界研究' },
  { keyword: '流通 小売 業界 就活 特徴', category: '業界研究' },
  { keyword: '食品 業界 就活 特徴 倍率', category: '業界研究' },
  { keyword: '自動車 業界 就活 将来性', category: '業界研究' },
  { keyword: '化学 業界 就活 理系 職種', category: '業界研究' },
  { keyword: '製薬 業界 就活 MR 仕事', category: '業界研究' },
  { keyword: '航空 業界 就活 CA 地上職 倍率', category: '業界研究' },
  { keyword: 'ホテル 業界 就活 仕事内容 魅力', category: '業界研究' },
  { keyword: '旅行 業界 就活 将来性 問題', category: '業界研究' },
  { keyword: '教育 業界 就活 公務員 民間 違い', category: '業界研究' },
  { keyword: '医療 業界 就活 職種 一覧', category: '業界研究' },
  { keyword: 'ゲーム 業界 就活 職種 倍率', category: '業界研究' },
  { keyword: 'エンタメ 業界 就活 音楽 映画', category: '業界研究' },
  { keyword: 'コンサル 業界 倍率 ランキング', category: '業界研究' },
  { keyword: '外資 業界 就活 特徴 難しい', category: '業界研究' },
  { keyword: '外資コンサル 就活 倍率 選考', category: '業界研究' },
  { keyword: '外資金融 就活 倍率 日本人', category: '業界研究' },
  { keyword: 'SIer 業界 就活 仕事内容 向き不向き', category: '業界研究' },
  { keyword: 'Web系 就活 自社開発 受託 違い', category: '業界研究' },
  { keyword: 'インフラ エンジニア 就活 将来性', category: '業界研究' },
  { keyword: 'フィンテック 業界 就活 注目', category: '業界研究' },
  { keyword: 'AI 業界 就活 エンジニア 採用', category: '業界研究' },
  { keyword: 'ブロックチェーン 業界 就活 現状', category: '業界研究' },
  { keyword: 'スタートアップ 業界 就活 魅力 注意', category: '業界研究' },
  { keyword: 'ベンチャー 業界 就活 大手 どちら', category: '業界研究' },
  { keyword: '公務員 業界 国家 地方 違い', category: '業界研究' },
  { keyword: '官公庁 就活 民間 との違い 特徴', category: '業界研究' },
  { keyword: 'NPO NGO 就活 特徴 年収', category: '業界研究' },
  { keyword: '社会人 3年後 離職率 業界別', category: '業界研究' },
  { keyword: '平均年収 業界 ランキング 最新', category: '業界研究' },
  { keyword: '残業 少ない 業界 ランキング', category: '業界研究' },
  { keyword: '福利厚生 充実 業界 ランキング', category: '業界研究' },
  { keyword: '成長 できる 業界 就活 選び方', category: '業界研究' },
  { keyword: '将来 なくなる 仕事 業界 就活', category: '業界研究' },
  { keyword: '就活 業界 絞り方 コツ', category: '業界研究' },
  { keyword: '業界 研究 いつから 始める', category: '業界研究' },
  { keyword: '業界 地図 2026 おすすめ', category: '業界研究' },
  { keyword: '業界 説明会 質問 例文', category: '業界研究' },
  { keyword: '業界 社員 話 聞く 方法', category: '業界研究' },
  { keyword: '業界 トレンド 調べ方 就活', category: '業界研究' },
  { keyword: '就活 異業種 転職 難易度', category: '業界研究' },
  { keyword: 'B to B B to C 違い 就活', category: '業界研究' },
  { keyword: '就活 業界 複数 受ける 理由', category: '業界研究' },
  { keyword: '就活 業界 絞りすぎ リスク', category: '業界研究' },
  { keyword: '就活 文系 理系 向いてる 業界', category: '業界研究' },
  { keyword: '就活 体育会系 向いてる 業界', category: '業界研究' },
  { keyword: '就活 文系 年収 高い 業界', category: '業界研究' },
  { keyword: '就活 理系 向いてる 業界 一覧', category: '業界研究' },
  { keyword: 'ブライダル 業界 就活 特徴 将来性', category: '業界研究' },
  { keyword: 'コスメ 美容 業界 就活 特徴', category: '業界研究' },
  { keyword: 'アパレル 業界 就活 年収 将来性', category: '業界研究' },
  { keyword: '物流 業界 就活 ドライバー 総合職', category: '業界研究' },
  { keyword: '建設 建築 業界 就活 特徴', category: '業界研究' },
  { keyword: 'エネルギー 業界 就活 電力 ガス', category: '業界研究' },
  { keyword: '農業 業界 就活 特徴 就職 難易度', category: '業界研究' },
  { keyword: 'フードテック 業界 就活 注目', category: '業界研究' },
  { keyword: 'HRテック 業界 就活 注目', category: '業界研究' },
  { keyword: 'サービス 業界 就活 難易度', category: '業界研究' },
  { keyword: '就活 総合職 一般職 違い', category: '業界研究' },
  { keyword: '就活 職種 一覧 説明', category: '業界研究' },
  { keyword: '就活 総合職 転勤 嫌 対策', category: '業界研究' },
  { keyword: '就活 一般職 倍率 高い 理由', category: '業界研究' },
  { keyword: '就活 地元 就職 Uターン 転職', category: '業界研究' },
  { keyword: '就活 地方 都市 年収 差', category: '業界研究' },
  { keyword: '就活 職種 向き不向き 診断', category: '業界研究' },

  // ===== 企業研究 =====
  { keyword: '企業研究 やり方 新卒 就活', category: '企業研究' },
  { keyword: '企業研究 項目 まとめ 方法', category: '企業研究' },
  { keyword: '企業研究 ノート 作り方', category: '企業研究' },
  { keyword: '企業研究 情報 集め方 方法', category: '企業研究' },
  { keyword: '企業研究 いつから 始める', category: '企業研究' },
  { keyword: '会社 IR情報 読み方 就活', category: '企業研究' },
  { keyword: '有価証券報告書 読み方 就活', category: '企業研究' },
  { keyword: '企業 決算 見方 就活 使い方', category: '企業研究' },
  { keyword: '企業 ニュース 調べ方 就活', category: '企業研究' },
  { keyword: '就活 企業 口コミ サイト 信頼性', category: '企業研究' },
  { keyword: 'OpenWork 口コミ 見方 活用法', category: '企業研究' },
  { keyword: 'エンゲージ 口コミ 就活 活用', category: '企業研究' },
  { keyword: '転職会議 口コミ 新卒 参考 になる', category: '企業研究' },
  { keyword: '企業 平均年収 調べ方 就活', category: '企業研究' },
  { keyword: '企業 残業時間 調べ方 実態', category: '企業研究' },
  { keyword: '企業 離職率 調べ方 ブラック 見極め', category: '企業研究' },
  { keyword: '企業 有給取得率 確認 方法', category: '企業研究' },
  { keyword: '企業 育休 取得率 確認 就活', category: '企業研究' },
  { keyword: '企業 福利厚生 比較 就活', category: '企業研究' },
  { keyword: '企業 評判 調べる ツール 就活', category: '企業研究' },
  { keyword: '就活 ホワイト企業 ランキング 基準', category: '企業研究' },
  { keyword: '就活 ブラック企業 見極め 方法', category: '企業研究' },
  { keyword: '就活 優良企業 中小 探し方', category: '企業研究' },
  { keyword: 'BtoB 企業 なぜ 人気 就活', category: '企業研究' },
  { keyword: '隠れ優良企業 就活 探し方', category: '企業研究' },
  { keyword: '中小企業 就活 メリット デメリット', category: '企業研究' },
  { keyword: '大企業 中小企業 どちら 選ぶ 基準', category: '企業研究' },
  { keyword: '就活 企業 成長率 調べ方', category: '企業研究' },
  { keyword: '就活 企業 ESG 調べ方', category: '企業研究' },
  { keyword: '就活 企業 社風 調べ方', category: '企業研究' },
  { keyword: '就活 企業 文化 調べ方 ギャップ', category: '企業研究' },
  { keyword: '就活 企業 ビジョン ミッション 理解', category: '企業研究' },
  { keyword: '就活 子会社 親会社 どちら 受ける', category: '企業研究' },
  { keyword: '就活 持株会社 グループ会社 違い', category: '企業研究' },
  { keyword: '就活 上場 非上場 違い 就活 影響', category: '企業研究' },
  { keyword: '就活 プライム 市場 スタンダード 違い', category: '企業研究' },
  { keyword: '就活 外資 日系 就活 違い', category: '企業研究' },
  { keyword: '就活 海外展開 企業 調べ方', category: '企業研究' },
  { keyword: '就活 本命 企業 対策 時間 配分', category: '企業研究' },
  { keyword: '就活 滑り止め 企業 選び方', category: '企業研究' },
  { keyword: '就活 企業 説明会 必ず参加 必要', category: '企業研究' },
  { keyword: '就活 会社 見学 服装 マナー', category: '企業研究' },
  { keyword: '就活 企業 訪問 後 メール', category: '企業研究' },
  { keyword: '就活 面接 企業 深掘り 対策', category: '企業研究' },
  { keyword: '就活 なぜ 志望 理由 答え方', category: '企業研究' },
  { keyword: '就活 競合 企業 なぜ うちか 答え方', category: '企業研究' },
  { keyword: '就活 企業 課題 答え方 面接', category: '企業研究' },
  { keyword: '就活 企業 将来 ビジョン 語り方', category: '企業研究' },
  { keyword: '就活 仕事 内容 具体的 調べ方', category: '企業研究' },
  { keyword: '就活 職場 環境 聞き方 OB訪問', category: '企業研究' },
  { keyword: '就活 採用 情報 公式 見方', category: '企業研究' },
  { keyword: '就活 採用 人数 調べ方 倍率', category: '企業研究' },
  { keyword: '就活 OBOG 訪問 企業 理解 深める', category: '企業研究' },
  { keyword: '就活 採用 担当 LinkedIn つながる', category: '企業研究' },
  { keyword: '就活 企業 SNS フォロー 方法', category: '企業研究' },
  { keyword: '就活 企業 社員 ブログ 参考', category: '企業研究' },
  { keyword: '就活 企業 メディア 出演 チェック', category: '企業研究' },
  { keyword: '就活 企業 採用 パンフレット 活用', category: '企業研究' },
  { keyword: '就活 企業 メモ 管理 方法', category: '企業研究' },
  { keyword: '就活 企業研究 どこまで やれば OK', category: '企業研究' },
  { keyword: '就活 企業 比較 表 作り方', category: '企業研究' },
  { keyword: '就活 企業 魅力 3つ 言い方', category: '企業研究' },
  { keyword: '就活 企業 質問 何 聞けばいい', category: '企業研究' },
  { keyword: '就活 企業 内部 情報 入手 方法', category: '企業研究' },
  { keyword: '就活 企業研究 志望動機 つなげ方', category: '企業研究' },
  { keyword: '就活 企業 他社比較 答え方', category: '企業研究' },
  { keyword: '就活 企業研究 足りない 言われた', category: '企業研究' },
  { keyword: '就活 企業研究 深い 面接 通過', category: '企業研究' },
  { keyword: '就活 企業研究 ツール 無料', category: '企業研究' },
  { keyword: '就活 一部上場 大手 選ぶ 理由', category: '企業研究' },
  { keyword: '就活 企業 倒産 リスク 見分け方', category: '企業研究' },
  { keyword: '就活 企業 社会貢献 語り方', category: '企業研究' },
  { keyword: '就活 会社 雰囲気 肌で感じる 方法', category: '企業研究' },
  { keyword: '就活 働き方 リモート テレワーク 確認', category: '企業研究' },

  // ===== OB・OG訪問 =====
  { keyword: 'OB訪問 やり方 流れ 初めて', category: 'OB・OG訪問' },
  { keyword: 'OG訪問 メール 例文 送り方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 質問 一覧 例文', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 お礼 メール 例文', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 マナー 服装 場所', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 意味 ない 理由', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 しないと いけない 業界', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 何人 回れば いい 理想', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 聞くべき 仕事 内容', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 聞いてはいけない 質問', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 ランチ 費用 どちらが 払う', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 コーヒー お茶 どちらが 払う', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 断られた 次 どうする', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 社員 紹介 チェーン 方法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 就活 面接 有利 つながる', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 大学 キャリアセンター 使い方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 LinkedInで 探す 方法', category: 'OB・OG訪問' },
  { keyword: 'Matcher OB訪問 使い方 コツ', category: 'OB・OG訪問' },
  { keyword: 'ビズリーチ OB訪問 サービス 使い方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 アプリ 比較 おすすめ', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 Twitter 探す 方法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 知らない社員 メール 送り方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 依頼 断り方 礼儀', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 日程 調整 メール 例文', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 Zoom オンライン マナー', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 オフライン カフェ 場所 選び方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 録音 許可 マナー', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 メモ 取り方 まとめ', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 後 ES 志望動機 活かし方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 後 面接 話題 使い方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 紹介 してもらった 次 どうする', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 複数 同じ 企業 何回', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 先輩 どこで 見つける', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 同じ 大学 OB いない 対処', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 選考 関係 ある なし', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 選考 有利 不利 本当', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 逆質問 使える 例文', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 ドタキャン どうする 対処法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 最初 自己紹介 やり方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 最後 締め方 言葉', category: 'OB・OG訪問' },
  { keyword: 'OG訪問 女性 社員 聞くべき こと', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 理系 研究 仕事 聞き方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 コンサル 外資 対策', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 メーカー 仕事内容 聞き方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 金融 銀行 聞くこと', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 先輩 年次 どのくらい 話す', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 後輩 いない 社会人 探す方法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 インターン 先 社員 頼む 方法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 採用 担当者 OB違い 注意', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 年収 聞いても いい', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 しんどい 疲れた 対処法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 嫌がる 社員 いる 理由', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 大学院生 メリット', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 体験談 ブログ 参考', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 やらなかった 後悔 理由', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 お礼 LINE 送る マナー', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 名刺 交換 方法', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 ブラック 企業 見極め 質問', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 パワハラ 感じた 対処', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 秘密 保持 発言 気をつけること', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 ネット 口コミ 違う 理由', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 先輩 経験 活かす 志望動機', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 一般職 総合職 どちらに 聞く', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 会社 同士 バレ ない', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 時間 何時間 目安', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 事前 準備 チェックリスト', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 後 内定 出た 報告', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 就活 終わった 連絡 礼儀', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 複数社 管理 スプレッドシート', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 志望動機 話す 量 目安', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 初対面 ラポール 築き方', category: 'OB・OG訪問' },
  { keyword: 'OB訪問 逆求人 プロフィール 見せる', category: 'OB・OG訪問' },

  // ===== 就活スケジュール =====
  { keyword: '就活 スケジュール 2026 年 いつから', category: '就活スケジュール' },
  { keyword: '就活 解禁 2026 3月 何が始まる', category: '就活スケジュール' },
  { keyword: '就活 3年生 夏 やること 一覧', category: '就活スケジュール' },
  { keyword: '就活 3年生 秋 冬 やること', category: '就活スケジュール' },
  { keyword: '就活 4年生 4月 内定 目標', category: '就活スケジュール' },
  { keyword: '就活 早期 スケジュール 外資 コンサル', category: '就活スケジュール' },
  { keyword: '就活 6月 内定式 意味', category: '就活スケジュール' },
  { keyword: '就活 10月 内定式 入社式 準備', category: '就活スケジュール' },
  { keyword: '就活 年間 スケジュール 理系 文系', category: '就活スケジュール' },
  { keyword: '就活 何月 始める 理想 時期', category: '就活スケジュール' },
  { keyword: '就活 遅れた 挽回 方法', category: '就活スケジュール' },
  { keyword: '就活 遅い 4年生 秋 冬 間に合う', category: '就活スケジュール' },
  { keyword: '就活 早期選考 いつ 始まる 業界', category: '就活スケジュール' },
  { keyword: '就活 夏インターン 選考 時期', category: '就活スケジュール' },
  { keyword: '就活 冬インターン 時期 参加 方法', category: '就活スケジュール' },
  { keyword: '就活 説明会 いつから 参加', category: '就活スケジュール' },
  { keyword: '就活 エントリー いつから 受付', category: '就活スケジュール' },
  { keyword: '就活 本選考 いつ 始まる', category: '就活スケジュール' },
  { keyword: '就活 内定 いつ もらえる 平均', category: '就活スケジュール' },
  { keyword: '就活 内定 もらうまで 平均 期間', category: '就活スケジュール' },
  { keyword: '就活 何社 受ける 平均 データ', category: '就活スケジュール' },
  { keyword: '就活 終わる 時期 平均 いつ', category: '就活スケジュール' },
  { keyword: '就活 長引く 理由 対処法', category: '就活スケジュール' },
  { keyword: '就活 夏 終わらない 焦り 対処', category: '就活スケジュール' },
  { keyword: '就活 秋 冬 まだ 続ける 方法', category: '就活スケジュール' },
  { keyword: '就活 卒業後 就職 タイミング', category: '就活スケジュール' },
  { keyword: '就職留年 メリット デメリット', category: '就活スケジュール' },
  { keyword: '既卒 就活 難しい 方法', category: '就活スケジュール' },
  { keyword: '既卒 新卒 扱い 企業 条件', category: '就活スケジュール' },
  { keyword: '院生 就活 スケジュール 時期', category: '就活スケジュール' },
  { keyword: '大学院 就活 研究 両立 方法', category: '就活スケジュール' },
  { keyword: '修士 就活 理系 パターン', category: '就活スケジュール' },
  { keyword: '就活 休学 後 就活 タイミング', category: '就活スケジュール' },
  { keyword: '就活 留学 帰国後 スケジュール', category: '就活スケジュール' },
  { keyword: '就活 アルバイト 両立 スケジュール', category: '就活スケジュール' },
  { keyword: '就活 授業 両立 時間管理 方法', category: '就活スケジュール' },
  { keyword: '就活 複数 内定 比較 期限', category: '就活スケジュール' },
  { keyword: '就活 内定承諾 期限 いつまで', category: '就活スケジュール' },
  { keyword: '就活 内定 保留 どのくらい まで', category: '就活スケジュール' },
  { keyword: '就活 後半戦 秋冬 採用 企業', category: '就活スケジュール' },
  { keyword: '就活 マイナビ リクナビ 登録 いつ', category: '就活スケジュール' },
  { keyword: '就活 自己分析 いつ 終わらせる', category: '就活スケジュール' },
  { keyword: '就活 業界研究 いつ 終わらせる', category: '就活スケジュール' },
  { keyword: '就活 OB訪問 いつ 行く 理想', category: '就活スケジュール' },
  { keyword: '就活 SPI 対策 いつ 始める', category: '就活スケジュール' },
  { keyword: '就活 ES 提出 デッドライン 管理', category: '就活スケジュール' },
  { keyword: '就活 企業 エントリー 数 タイミング', category: '就活スケジュール' },
  { keyword: '就活 夏 インターン 終わった 次 何する', category: '就活スケジュール' },
  { keyword: '就活 冬 インターン 終わった 次 準備', category: '就活スケジュール' },
  { keyword: '就活 3月 まで スケジュール 逆算', category: '就活スケジュール' },
  { keyword: '就活 6月 まで スケジュール 計画', category: '就活スケジュール' },
  { keyword: '就活 ガントチャート 作り方 就活版', category: '就活スケジュール' },
  { keyword: '就活 スプレッドシート テンプレート', category: '就活スケジュール' },
  { keyword: '就活 カレンダー アプリ おすすめ 管理', category: '就活スケジュール' },
  { keyword: '就活 緊急 対策 残り 時間 少ない', category: '就活スケジュール' },
  { keyword: '就活 サマー インターン 終了後 本選考 流れ', category: '就活スケジュール' },
  { keyword: '就活 プレエントリー 締切 管理 方法', category: '就活スケジュール' },
  { keyword: '就活 優先 企業 決め方', category: '就活スケジュール' },
  { keyword: '就活 詰め込み 過ぎ 疲れ 対処', category: '就活スケジュール' },
  { keyword: '就活 スケジュール 管理 ノーション', category: '就活スケジュール' },
  { keyword: '就活 スケジュール 管理 Excel', category: '就活スケジュール' },
  { keyword: '就活 選考 重なる 対処法', category: '就活スケジュール' },
  { keyword: '就活 日程 変更 可能 範囲', category: '就活スケジュール' },
  { keyword: '就活 複数社 同日 面接 スケジュール', category: '就活スケジュール' },
  { keyword: '就活 内定 後 勉強 やること', category: '就活スケジュール' },
  { keyword: '就活 4月 内定 ない 原因', category: '就活スケジュール' },
  { keyword: '就活 5月 内定 ない 対処', category: '就活スケジュール' },
  { keyword: '就活 6月 内定 ない 諦め 考え方', category: '就活スケジュール' },
  { keyword: '就活 秋採用 企業 一覧 2026', category: '就活スケジュール' },
  { keyword: '就活 通年採用 企業 2026', category: '就活スケジュール' },
  { keyword: '就活 2月 3月 追い込み 企業探し', category: '就活スケジュール' },
  { keyword: '就活 全部終わった いつ 時期 次 やること', category: '就活スケジュール' },
  { keyword: '就活 内定 後 入社 準備 何する', category: '就活スケジュール' },
  { keyword: '就活 卒論 両立 いつから 大変', category: '就活スケジュール' },

  // ===== キャリア設計 =====
  { keyword: 'キャリア設計 新卒 やり方 方法', category: 'キャリア設計' },
  { keyword: 'キャリアビジョン 面接 答え方', category: 'キャリア設計' },
  { keyword: '20代 キャリア 考え方 新卒', category: 'キャリア設計' },
  { keyword: '30代 キャリア 設計 逆算', category: 'キャリア設計' },
  { keyword: 'キャリア 軸 見つけ方 就活', category: 'キャリア設計' },
  { keyword: 'キャリア 軸 例文 就活', category: 'キャリア設計' },
  { keyword: '就活 軸 なぜ 必要 説明', category: 'キャリア設計' },
  { keyword: '就活 軸 ない どうする', category: 'キャリア設計' },
  { keyword: '就活 やりたい こと ない 対処', category: 'キャリア設計' },
  { keyword: '就活 向いてる 仕事 見つけ方', category: 'キャリア設計' },
  { keyword: '就活 向いてる 仕事 診断 無料', category: 'キャリア設計' },
  { keyword: '就活 向いてない 仕事 やめる 決断', category: 'キャリア設計' },
  { keyword: '就活 価値観 見つけ方 ツール', category: 'キャリア設計' },
  { keyword: '働き方 価値観 就活 面接 話し方', category: 'キャリア設計' },
  { keyword: 'ワークライフバランス 就活 答え方', category: 'キャリア設計' },
  { keyword: '就活 福利厚生 重視 理由 答え方', category: 'キャリア設計' },
  { keyword: '就活 給与 重視 答え方 面接', category: 'キャリア設計' },
  { keyword: '就活 年収 目標 面接 言い方', category: 'キャリア設計' },
  { keyword: 'キャリアパス 就活 面接 説明方法', category: 'キャリア設計' },
  { keyword: 'ゼネラリスト スペシャリスト 就活 選択', category: 'キャリア設計' },
  { keyword: '転職 前提 就活 企業 選び方', category: 'キャリア設計' },
  { keyword: '転職 しやすい 会社 新卒 選び方', category: 'キャリア設計' },
  { keyword: '新卒 3年 転職 業界 変え方', category: 'キャリア設計' },
  { keyword: '第二新卒 就活 有利 方法', category: 'キャリア設計' },
  { keyword: '新卒 就活 失敗 後悔 しない 選び方', category: 'キャリア設計' },
  { keyword: '就活 大企業 vs ベンチャー 比較', category: 'キャリア設計' },
  { keyword: '就活 安定 求める 企業 選び方', category: 'キャリア設計' },
  { keyword: '就活 成長 環境 企業 選び方', category: 'キャリア設計' },
  { keyword: '就活 人の役 立つ 仕事 選び方', category: 'キャリア設計' },
  { keyword: '就活 社会貢献 仕事 例 業界', category: 'キャリア設計' },
  { keyword: '就活 スキル 身につく 仕事 選び方', category: 'キャリア設計' },
  { keyword: '就活 グローバル 仕事 選び方', category: 'キャリア設計' },
  { keyword: '就活 海外 駐在 する 会社 選び方', category: 'キャリア設計' },
  { keyword: '就活 在宅 テレワーク 多い 会社', category: 'キャリア設計' },
  { keyword: '就活 フレックス 制度 活用 会社', category: 'キャリア設計' },
  { keyword: '就活 副業 OK 会社 選び方', category: 'キャリア設計' },
  { keyword: '就活 資格 取得 支援 会社 選び方', category: 'キャリア設計' },
  { keyword: '就活 ダイバーシティ 重視 会社', category: 'キャリア設計' },
  { keyword: '就活 女性 活躍 推進 会社', category: 'キャリア設計' },
  { keyword: '就活 産休 育休 取りやすい 会社', category: 'キャリア設計' },
  { keyword: '就活 LGBT フレンドリー 企業', category: 'キャリア設計' },
  { keyword: '就活 障がい者 就職 支援 方法', category: 'キャリア設計' },
  { keyword: '就活 MBTI 活用 キャリア 決め方', category: 'キャリア設計' },
  { keyword: '就活 ストレングスファインダー 活用', category: 'キャリア設計' },
  { keyword: '就活 RIASEC 職業興味 診断', category: 'キャリア設計' },
  { keyword: '就活 エニアグラム キャリア 活用', category: 'キャリア設計' },
  { keyword: '就活 自己理解 深める 本 おすすめ', category: 'キャリア設計' },
  { keyword: '就活 メンター 探す 方法', category: 'キャリア設計' },
  { keyword: '就活 キャリア相談 誰に すればいい', category: 'キャリア設計' },
  { keyword: '就活 親 意見 どう 扱う べきか', category: 'キャリア設計' },
  { keyword: '就活 親が 公務員 勧める 対処', category: 'キャリア設計' },
  { keyword: '就活 内定ブルー 原因 克服', category: 'キャリア設計' },
  { keyword: '就活 内定後 入社 楽しみ 見つけ方', category: 'キャリア設計' },
  { keyword: '就活 会社 選ぶ 基準 何が 重要', category: 'キャリア設計' },
  { keyword: '就活 直感 大事 企業 選び方', category: 'キャリア設計' },
  { keyword: '就活 逃げ 就職 後悔 しない 方法', category: 'キャリア設計' },
  { keyword: '就活 モチベーション 上がらない 対処', category: 'キャリア設計' },
  { keyword: '就活 つらい 乗り越え方', category: 'キャリア設計' },
  { keyword: '就活 メンタル 保つ 方法', category: 'キャリア設計' },
  { keyword: '就活 ストレス 発散 方法', category: 'キャリア設計' },
  { keyword: '就活 うつ 症状 なりそう 相談', category: 'キャリア設計' },
  { keyword: '就活 サポート センター 無料 相談', category: 'キャリア設計' },
  { keyword: '就活 諦め 考える 前 やること', category: 'キャリア設計' },
  { keyword: '就活 失敗 した 次 やること', category: 'キャリア設計' },
  { keyword: '就活 企業 自分 合う 感じ方', category: 'キャリア設計' },
  { keyword: '就活 直感 第一印象 信じる', category: 'キャリア設計' },
  { keyword: '就活 成功 共通点 やること', category: 'キャリア設計' },
  { keyword: '就活 早い 内定 いつ 有効 期限', category: 'キャリア設計' },
  { keyword: '就活 なんとなく 決める どう 感じる', category: 'キャリア設計' },
  { keyword: 'キャリア 10年後 描き方 就活版', category: 'キャリア設計' },
  { keyword: 'キャリア 棚卸し やり方 新卒', category: 'キャリア設計' },
  { keyword: 'キャリア 形成 初期 大事 こと', category: 'キャリア設計' },
  { keyword: '新卒 入社後 目標 設定 方法', category: 'キャリア設計' },
  { keyword: '就活 夢 なくても 就職 できる か', category: 'キャリア設計' },
  { keyword: '就活 情熱 見つけ方 やりたいこと', category: 'キャリア設計' },
  { keyword: '就活 お金 よりも 働き方 重視', category: 'キャリア設計' },

  // ===== 留学・海外就活 =====
  { keyword: '留学 就活 有利 本当に そうか', category: '留学・海外就活' },
  { keyword: '留学 経験 ES 書き方 例文', category: '留学・海外就活' },
  { keyword: '留学 経験 面接 話し方 コツ', category: '留学・海外就活' },
  { keyword: '留学 帰国後 就活 スケジュール', category: '留学・海外就活' },
  { keyword: '留学 就活 遅れ 挽回 方法', category: '留学・海外就活' },
  { keyword: '短期留学 就活 評価 される', category: '留学・海外就活' },
  { keyword: '交換留学 就活 アピール 方法', category: '留学・海外就活' },
  { keyword: '語学留学 就活 活かし方', category: '留学・海外就活' },
  { keyword: '留学 TOEIC スコア どのくらい 必要', category: '留学・海外就活' },
  { keyword: '英語力 就活 どのくらい 必要', category: '留学・海外就活' },
  { keyword: 'TOEIC 600 700 800 就活 違い', category: '留学・海外就活' },
  { keyword: 'TOEIC 就活 スコア 書かない 基準', category: '留学・海外就活' },
  { keyword: '外資系 就活 英語 試験 対策', category: '留学・海外就活' },
  { keyword: '外資系 就活 英語 面接 対策', category: '留学・海外就活' },
  { keyword: '外資系 就活 英語 ES 書き方', category: '留学・海外就活' },
  { keyword: '外資系 就活 倍率 難易度 2026', category: '留学・海外就活' },
  { keyword: '外資系 就活 インターン 参加 方法', category: '留学・海外就活' },
  { keyword: '外資系 就活 文系 入れる 職種', category: '留学・海外就活' },
  { keyword: '外資系 就活 理系 採用 特徴', category: '留学・海外就活' },
  { keyword: '外資 コンサル 就活 難易度 対策', category: '留学・海外就活' },
  { keyword: '外資 投資銀行 就活 倍率 選考', category: '留学・海外就活' },
  { keyword: '外資 メーカー 就活 特徴 職種', category: '留学・海外就活' },
  { keyword: '外資 IT 就活 就活 特徴 方法', category: '留学・海外就活' },
  { keyword: 'グローバル 就活 日系 外資 どちら', category: '留学・海外就活' },
  { keyword: '海外就職 新卒 日本人 可能 か', category: '留学・海外就活' },
  { keyword: '海外 就職 準備 新卒 やること', category: '留学・海外就活' },
  { keyword: '海外 就職 ビザ 取り方 新卒', category: '留学・海外就活' },
  { keyword: '海外 就職 英語力 どのくらい 必要', category: '留学・海外就活' },
  { keyword: 'シンガポール 就職 新卒 日本人', category: '留学・海外就活' },
  { keyword: 'アメリカ 就職 日本人 新卒 難易度', category: '留学・海外就活' },
  { keyword: 'ドイツ 就職 新卒 日本人 エンジニア', category: '留学・海外就活' },
  { keyword: 'イギリス 就職 日本人 新卒 方法', category: '留学・海外就活' },
  { keyword: 'カナダ ワーホリ 就職 新卒', category: '留学・海外就活' },
  { keyword: '海外 就職 失敗 帰国後 日本 就活', category: '留学・海外就活' },
  { keyword: '海外 駐在 新卒 多い 会社', category: '留学・海外就活' },
  { keyword: '海外 駐在 行ける 仕事 就職', category: '留学・海外就活' },
  { keyword: '海外 駐在員 生活 年収 実態', category: '留学・海外就活' },
  { keyword: '留学 中 就活 できる 方法', category: '留学・海外就活' },
  { keyword: '留学 中 オンライン 選考 対応 方法', category: '留学・海外就活' },
  { keyword: '留学 中 インターン 応募 できる か', category: '留学・海外就活' },
  { keyword: '留学 就活 タイミング 帰国 時期', category: '留学・海外就活' },
  { keyword: '留学 就活 スタート 遅れ 不利', category: '留学・海外就活' },
  { keyword: '留学 理由 ES 答え方 例文', category: '留学・海外就活' },
  { keyword: '留学 語学 以外 学んだこと 答え方', category: '留学・海外就活' },
  { keyword: '留学 挫折 経験 面接 話し方', category: '留学・海外就活' },
  { keyword: '留学 成長 アピール 具体的 方法', category: '留学・海外就活' },
  { keyword: '留学 就活 ガクチカ 活かし方', category: '留学・海外就活' },
  { keyword: '留学経験 自己PR 書き方 例', category: '留学・海外就活' },
  { keyword: '留学 ESで 弱み 感じた こと 答え方', category: '留学・海外就活' },
  { keyword: '留学 コミュニケーション 能力 アピール', category: '留学・海外就活' },
  { keyword: '留学 異文化 理解 就活 活かす', category: '留学・海外就活' },
  { keyword: 'TOEFL IELTS 就活 有効か', category: '留学・海外就活' },
  { keyword: '英語 資格 就活 どれ 有効', category: '留学・海外就活' },
  { keyword: '英語 ビジネスレベル 就活 意味', category: '留学・海外就活' },
  { keyword: '英語 就活 どの職種 で 使う', category: '留学・海外就活' },
  { keyword: '留学 コスパ 就活 費用対効果', category: '留学・海外就活' },
  { keyword: '留学 行かなかった 就活 不利 本当', category: '留学・海外就活' },
  { keyword: '留学 意味なかった 就活 にどう 言う', category: '留学・海外就活' },
  { keyword: '留学 後悔 就活 ない ために すること', category: '留学・海外就活' },
  { keyword: '留学 経験 ない 外資 受ける 方法', category: '留学・海外就活' },
  { keyword: '留学 奨学金 もらえた 就活 アピール', category: '留学・海外就活' },
  { keyword: 'ギャップイヤー 就活 大丈夫 企業', category: '留学・海外就活' },
  { keyword: 'ダブルディグリー 就活 評価 方法', category: '留学・海外就活' },
  { keyword: '海外 大学院 就活 日本企業 可能', category: '留学・海外就活' },
  { keyword: '日本 企業 海外拠点 就活 選ぶ 方法', category: '留学・海外就活' },
  { keyword: '海外 就職 SNS LinkedIn 使い方', category: '留学・海外就活' },
  { keyword: '留学 期間 3ヶ月 6ヶ月 1年 違い 就活', category: '留学・海外就活' },
  { keyword: '海外 インターン 日本就活 有利か', category: '留学・海外就活' },
  { keyword: '海外 ボランティア 就活 評価', category: '留学・海外就活' },
  { keyword: '留学生 採用 日本企業 どこ 調べ方', category: '留学・海外就活' },
  { keyword: 'グローバル人材 採用 企業 一覧', category: '留学・海外就活' },
  { keyword: '英語 面接 自己紹介 例文 就活', category: '留学・海外就活' },
  { keyword: '英語 面接 強み 弱み 答え方', category: '留学・海外就活' },
  { keyword: '英語 面接 対策 何 すれば いい', category: '留学・海外就活' },
  { keyword: '英語 面接 練習 方法 独学', category: '留学・海外就活' },
  { keyword: '英語 面接 通過 コツ 外資', category: '留学・海外就活' },
  { keyword: '英語 グループディスカッション 対策', category: '留学・海外就活' },
  { keyword: '外資 カルチャーフィット 面接 対策', category: '留学・海外就活' },
]

async function seed() {
  const batchSize = 100
  let totalInserted = 0

  for (let i = 0; i < keywords.length; i += batchSize) {
    const batch = keywords.slice(i, i + batchSize)
    const { error } = await supabase
      .from('keywords')
      .upsert(batch, { onConflict: 'keyword' })
    if (error) {
      console.error(`バッチ ${Math.floor(i / batchSize) + 1} でエラー:`, error)
      throw error
    }
    totalInserted += batch.length
    console.log(`${totalInserted}/${keywords.length}件投入完了`)
  }
  console.log(`\n合計${keywords.length}件のキーワードを投入しました`)
}

seed().catch(console.error)
